name: os_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6

  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  camera: ^0.10.0+5
  image: ^3.2.2
  google_ml_kit: ^0.13.0
  tflite_flutter: ^0.9.0

  get_it: ^7.2.0

  tuple: ^2.0.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  freezed: ^2.3.2
  json_serializable: ^6.5.4

  hive_generator: ^2.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/