name: os_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6

  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  tflite_flutter: ^0.9.0
  camera: ^0.10.0+5
  path_provider: ^2.0.11
  path: ^1.8.2
  google_ml_kit: ^0.13.0
  image: ^3.2.2
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.1.7
  sqflite: ^2.2.2
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  freezed: ^2.3.2
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true